// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2kmex8ASnIYVSrKl7TF0DvtSEqR5NR1A',
    appId: '1:713397245539:web:9519506cfc919ec2a24a56',
    messagingSenderId: '713397245539',
    projectId: 'my-backend-f110b',
    authDomain: 'my-backend-f110b.firebaseapp.com',
    storageBucket: 'my-backend-f110b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqZ9Bc9GgYvPBimJ3rKnZGvVHjuPenLw',
    appId: '1:713397245539:android:94997128a1b6ad0ba24a56',
    messagingSenderId: '713397245539',
    projectId: 'my-backend-f110b',
    storageBucket: 'my-backend-f110b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilw6OxvbpUnUPvoUIqiiBwudog4L0EsI',
    appId: '1:713397245539:ios:bf1e2b3e7dd93f5ea24a56',
    messagingSenderId: '713397245539',
    projectId: 'my-backend-f110b',
    storageBucket: 'my-backend-f110b.firebasestorage.app',
    iosBundleId: 'com.example.myFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilw6OxvbpUnUPvoUIqiiBwudog4L0EsI',
    appId: '1:713397245539:ios:bf1e2b3e7dd93f5ea24a56',
    messagingSenderId: '713397245539',
    projectId: 'my-backend-f110b',
    storageBucket: 'my-backend-f110b.firebasestorage.app',
    iosBundleId: 'com.example.myFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2kmex8ASnIYVSrKl7TF0DvtSEqR5NR1A',
    appId: '1:713397245539:web:beef2affbbaf971aa24a56',
    messagingSenderId: '713397245539',
    projectId: 'my-backend-f110b',
    authDomain: 'my-backend-f110b.firebaseapp.com',
    storageBucket: 'my-backend-f110b.firebasestorage.app',
  );
}
